- deployment/helm/edc-controlplane/templates/deployment.yaml
- deployment/helm/edc-dataplane/templates/deployment.yaml
- edc-controlplane/edc-controlplane-cosmosdb/src/main/docker/Dockerfile
- edc-dataplane/src/main/docker/Dockerfile
Replaces __openjdk:11-jre-slim-buster__ docker base image by __gcr.io/distroless/java11-debian11__ to become distroless.
configuration.properties path has been adjusted within each helm chart.
<sub> Denis Neuling <denis.neuling@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)
> Feature: distroless docker images

- .github/workflows/build.yaml
Sets the "edc" git submodules version to [3305340d6a19ba919540d28a731b3cab6d23857a](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/3305340d6a19ba919540d28a731b3cab6d23857a).
<sub> Denis Neuling <denis.neuling@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)
> Bumb edc to 3305340d6a19ba919540d28a731b3cab6d23857a

- .github/workflows/build.yaml
- CHANGELOG.md
- deployment/helm/edc-controlplane/Chart.yaml
- deployment/helm/edc-controlplane/values.yaml
- deployment/helm/edc-dataplane/Chart.yaml
- deployment/helm/edc-dataplane/values.yaml
- edc-controlplane/pom.xml
- edc-dataplane/pom.xml
- edc-extensions/pom.xml
- pom.xml
As requested by [Sigi](https://github.com/Siegfriedk) the project shall be renamed to `product-edc` to align with the naming convention within the catenax-ng organization leading to better assignability. 
This Pull-Request changes all links / references containing 'catena-x-edc' to 'product-edc' and **shall be merged after (!)** actually [renaming the repository](https://github.com/catenax-ng/catena-x-edc/settings).
<sub> Denis Neuling <denis.neuling@mercedes-benz.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
> Rename project to product-edc

- edc-controlplane/edc-controlplane-cosmosdb/pom.xml
- edc-controlplane/edc-controlplane-memory/pom.xml
- pom.xml
The repo was not buildable anymore with the new edc version
> Remove all in-memory stores deps which are now default

- deployment/helm/edc-controlplane/values.yaml
- deployment/helm/edc-dataplane/values.yaml
These are not needed, because they are only used in the `vault-fs` extension of the edc.
> Remove keystore configurations

- edc-controlplane/edc-controlplane-memory/README.md
- edc-controlplane/edc-controlplane-memory/pom.xml
Introduces the org.eclipse.dataspaceconnector:iam-daps and org.eclipse.dataspaceconnector:oauth2-core modules to the [controlplane-memory](https://github.com/catenax-ng/product-edc/tree/feature/control-plane-memory-iam-daps/edc-controlplane/edc-controlplane-memory) in replacement of org.eclipse.dataspaceconnector:iam-mock. Closes #110 
> Replace iam-mock by iam-daps at controlplane-memory

- .github/workflows/publish-new-release.yml
Update the publish release workflow to upload packaged helm charts to [gh-pages](https://github.com/catenax-ng/product-edc/tree/gh-pages). Closes #138
Contrary to just using the [gh chart-releaser-action](https://github.com/helm/chart-releaser-action), which creates Github Releases on its own, this approach implements a custom solution utilizing our existing release workflow.
> Upload released helm charts to gh-pages

- edc-controlplane/README.md
there was a request to replace the asset endpoint with one that is able to deliver real json
> update control plane link for json date source

- edc-tests/src/main/resources/deployment/helm/all-in-one/Chart.yaml
According to the [helm documentation](https://helm.sh/docs/chart_best_practices/dependencies/#versions) Chart dependency versions must be expressed using semver and can contain comparison and logical operators - so reasonable to utilize them for locally present charts the [all-in-one Chart](https://github.com/catenax-ng/product-edc/tree/feature/edc-tests-helm-aio-dependency-version-range/edc-tests/src/main/resources/deployment/helm/all-in-one/Chart.yaml) is dependent on. 
> Use semver version range >=0.0.1 for locally present dependencies

- edc-extensions/dataplane-selector-configuration/README.md
Make ``<data-plane-id>`` visible in table.
Remove trailing slash in public url Example -> this causes double slashes occurring in end-to-end flow.
> Minor changes to the Readme

- docs/data-transfer/Transfer Data.md
> improve formatting of 'Transfer Data.md'

- edc-controlplane/edc-controlplane-memory/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
> replace distroless with alpine image

- README.md
This PR adds a separation of commands for Unix and Windows separately while publishing Maven Local artifacts. This is important because in some Windows versions, the command Pskip is not recognized.
> Add windows command in README.md for EDC publishToMavenLocal

- charts/tractusx-connector/values.yaml
- docs/samples/Local TXDC Setup.md
> update setup docu

- .github/workflows/trivy.yml
Seems like the Trivy action workflow breaks really often:
https://github.com/catenax-ng/product-edc/actions/workflows/trivy.yml
A lot of these failures report this error:
```log
WARN	Increase --timeout value
FATAL	image scan error: scan error: scan failed: failed analysis: analyze error: timeout: context deadline exceeded
``` 
According to [the documentation](https://github.com/aquasecurity/trivy-action) the default timeout is 5m, this PR will raise it to 10m
> Increase trivy timeout

- docs/samples/README.md
- docs/samples/data-plane-http-oauth2.md
- docs/samples/oauth2-provision.md
- edc-controlplane/edc-controlplane-base/pom.xml
- edc-dataplane/edc-dataplane-base/pom.xml
- edc-tests/src/main/resources/deployment/helm/omejdn/templates/configmap.yaml
- edc-tests/src/test/resources/org/eclipse/tractusx/edc/tests/features/HttpProxyDataTransfer.feature
- pom.xml
replaces `provision-oauth2` with `data-plane-http-oauth2`
apparently there can be only 1 provisioner acting on the provider side modifying the content data address, otherwise they'll clash, as we're introducing the additional headers provisioner in #732 , the behavior of handling oauth2 authorization can be done in the data-plane directly with the `data-plane-http-oauth2` (that in fact will replace the provision extension in its entirety)
NOTE: this needs to be merged before #732, otherwise the business tests there could not pass because the provisioner issue I mentioned.
> Replace `provision-oauth2` with `data-plane-http-oauth2`

- edc-controlplane/edc-controlplane-base/pom.xml
- edc-extensions/pom.xml
- edc-extensions/provision-additional-headers/README.md
- edc-extensions/provision-additional-headers/pom.xml
- edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisionedResource.java
- edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisioner.java
- edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersResourceDefinition.java
- edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersResourceDefinitionGenerator.java
- edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/ProvisionAdditionalHeadersExtension.java
- edc-extensions/provision-additional-headers/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisionedResourceTest.java
- edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisionerTest.java
- edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersResourceDefinitionGeneratorTest.java
- edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersResourceDefinitionTest.java
- edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/ProvisionAdditionalHeadersExtensionTest.java
- pom.xml
provides a provision extension to enrich the `HttpDataAddress` with an header containing the contract id
to being able to forward that information to the backend data source
registers a resource definition and a provisioner that on the provider side will modify the content data address adding the contract id header: `Edc-Contract-Id`
> Add contract id to data source http call

- edc-controlplane/edc-controlplane-base/pom.xml
- edc-dataplane/edc-dataplane-base/pom.xml
- edc-extensions/cx-oauth2/pom.xml
- edc-extensions/dataplane-selector-configuration/pom.xml
- edc-extensions/hashicorp-vault/pom.xml
- edc-extensions/provision-additional-headers/pom.xml
- pom.xml
Bump EDC to the version that uses jackson 2.14.2
overriding dependencies is not a good practice as it brings unneeded complexity. 
Since we're the main contributors of the upstream project, we should update there first and then inherit the version.
We should do the same for nimbus-jose.
> Use upstream jackson version

- pom.xml
Updates EDC to 20220220.
Compared to the current 20230213 it brings these new commits:
```
bab97cccf fix: catalog pagination (#2494)
f97ff31ab fix: disable flaky ADF test (#2497)
e7945dafa fix: adding missing wrapping transaction blocks in `SqlPolicyDefinitionStore` (#2495)
3d0bd14d6 refactor: move api modules from control-plane to extensions module (#2486)
a89344431 chore: remove unused dependency (#2485)
532f02c30 build(deps): bump com.auth0:java-jwt from 4.2.2 to 4.3.0 (#2484)
```
no braking changes contained
> Bump EDC to 20220220

- charts/edc-controlplane/Chart.yaml
- charts/edc-controlplane/README.md
- charts/edc-controlplane/README.md.gotmpl
- charts/edc-controlplane/templates/configmap-env.yaml
- charts/edc-controlplane/templates/configmap.yaml
- charts/edc-controlplane/templates/deployment.yaml
- charts/edc-controlplane/templates/hpa.yaml
- charts/edc-controlplane/templates/imagepullsecret.yaml
- charts/edc-controlplane/templates/ingress.yaml
- charts/edc-controlplane/templates/service.yaml
- charts/edc-controlplane/templates/serviceaccount.yaml
- charts/edc-controlplane/values.yaml
- charts/edc-dataplane/Chart.yaml
- charts/edc-dataplane/README.md
- charts/edc-dataplane/README.md.gotmpl
- charts/edc-dataplane/templates/configmap-env.yaml
- charts/edc-dataplane/templates/configmap.yaml
- charts/edc-dataplane/templates/deployment.yaml
- charts/edc-dataplane/templates/hpa.yaml
- charts/edc-dataplane/templates/imagepullsecret.yaml
- charts/edc-dataplane/templates/ingress.yaml
- charts/edc-dataplane/templates/service.yaml
- charts/edc-dataplane/templates/serviceaccount.yaml
- charts/edc-dataplane/values.yaml
- edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-memory/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
Adds some license headers
Changes some reference from product-edc to tractusx
This was requested to being able to merge release 0.1.5 to tractusx (https://github.com/eclipse-tractusx/tractusx-edc/pull/86).
There's also an issue that asks to update all the headers to make them match the Eclipse recommendations (https://github.com/eclipse-tractusx/tractusx-edc/issues/88)
> chore: update headers and references for tractusx

- charts/tractusx-connector/values.yaml
Correct metrics port for controlplane and dataplane to use the same port as defined in Dockerfile.
> bugfix: correct the metrics port

- .github/workflows/helm-chart-release.yaml
Taken from: https://github.com/eclipse-tractusx/tractusx-edc/blob/8b1e765a6f509fee1b73fdd8974f6e8aefe13e08/.github/workflows/helm-chart-release.yaml
> fix: backport helm-chart-release ci workflow from tractusx

- .github/workflows/kics.yml
Pins the version of the KICS action to [1.5](https://github.com/Checkmarx/kics-github-action/releases/tag/v1.5) because it was previously set to `master`, which caused compile errors.
As far as I could determine the problem has to do with OpenSSH and/or webpack. 
Generally, pinned versions are preferable to ensure stable builds.
> fix: pin KICS version to v1.5

- docs/migration/Version_0.1.x_0.3.x.md
Data providers (like the simple data exchanger, SDE) are used to add multiple BPNs as a constraint to control the access to certain assets. So far, with version 0.1.6, it was possible to do this by using an IN operator and use an array of BPNs in the `rightExpression#value` of the respective `AtomicConstraint`.
With version 0.3.0 it is necessary to use an `orconstraint` instead of the IN operator. Thus, it is meaningful for the data providers to adjust their data provisioning pipeline accordingly.
The PR adds a bullet point to the changes of the Management API that expresses the above change related to the Business Partner Validation Extension.
> Add the hint to use an orconstraint instead of a IN operator for the Business Partner Validation Extension
