edc-controlplane/edc-controlplane-cosmosdb/pom.xml
edc-dataplane/pom.xml
pom.xml

*  Collect all non-sample/launcher edc artifacts within pom's dependencyManagement
* Revise control/data plane dependencies
<sub> Denis Neuling <denis.neuling@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

Feature: classpath hardening

---

edc-controlplane/edc-controlplane-memory/src/main/java/net/catenax/edc/controlplane/ControlPlaneController.java

Signed-off-by: Dominik Pinsel <email@dominik-pinsel.com>

fix createAsset API in ControlPlaneController.java

---

edc-controlplane/README.md

Fix typo in ContractDefinitions URL in the docu

---

deployment/helm/README.md
deployment/helm/edc-controlplane/Chart.yaml
deployment/helm/edc-controlplane/README.md
deployment/helm/edc-controlplane/README.md.gotmpl
deployment/helm/edc-controlplane/values.yaml
deployment/helm/edc-dataplane/Chart.yaml
deployment/helm/edc-dataplane/README.md
deployment/helm/edc-dataplane/README.md.gotmpl
deployment/helm/edc-dataplane/values.yaml

Adding more details to each of the helm chart Readme files using [helm-docs tool](https://github.com/norwoodj/helm-docs).

Update chart readme's

---

.mvn/jvm.config
edc-extensions/business-partner-validation/pom.xml
edc-extensions/business-partner-validation/src/test/java/net/catenax/edc/validation/businesspartner/BusinessPartnerValidationExtensionTest.java
edc-extensions/business-partner-validation/src/test/java/net/catenax/edc/validation/businesspartner/functions/AbstractBusinessPartnerValidationTest.java
edc-extensions/pom.xml
pom.xml

Update google java format dependency

---

edc-controlplane/edc-controlplane-base/README.md
edc-controlplane/edc-controlplane-base/pom.xml
edc-controlplane/edc-controlplane-memory/pom.xml
edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/pom.xml
edc-controlplane/edc-controlplane-postgresql/pom.xml
edc-controlplane/pom.xml
edc-dataplane/edc-dataplane-azure-vault/pom.xml
edc-dataplane/edc-dataplane-base/README.md
edc-dataplane/edc-dataplane-base/pom.xml
edc-dataplane/edc-dataplane-hashicorp-vault/pom.xml
edc-dataplane/pom.xml
edc-extensions/hashicorp-vault/pom.xml
pom.xml

This PR introduces for each the control-plane and data-plane a intermediary maven pom containing base dependencies.

Introduce controlplane-base and dataplane-base module

---

edc-tests/src/main/resources/deployment/helm/all-in-one/Chart.yaml

update edc chart versions in all-in-one deployment

---

edc-extensions/business-partner-validation/README.md
edc-extensions/business-partner-validation/src/main/java/net/catenax/edc/validation/businesspartner/functions/AbstractBusinessPartnerValidation.java

Follow up for  https://github.com/catenax-ng/product-edc/pull/221

Update BPN documentation

---

deployment/helm/README.md
edc-controlplane/README.md
edc-dataplane/README.md
edc-tests/src/main/resources/deployment/helm/all-in-one/Chart.yaml
edc-tests/src/main/resources/deployment/helm/all-in-one/templates/_helpers.tpl
edc-tests/src/main/resources/deployment/helm/all-in-one/templates/secret.yaml
edc-tests/src/main/resources/deployment/helm/all-in-one/values.yaml

Add documentation to deploy EDC settings as k8 secrets

---

docs/data-transfer/Transfer Data.md

fix documentation

---

CHANGELOG.md
edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/AbstractHashicorpVaultExtension.java
edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVaultHealthExtension.java
edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVaultVaultExtension.java

rename HashiCorp to Hashicorp

---

docs/data-transfer/Transfer Data.md
edc-extensions/business-partner-validation/src/main/java/net/catenax/edc/validation/businesspartner/BusinessPartnerValidationExtension.java
edc-extensions/business-partner-validation/src/main/java/net/catenax/edc/validation/businesspartner/functions/AbstractBusinessPartnerValidation.java
edc-tests/src/main/resources/deployment/helm/all-in-one/values.yaml
edc-tests/src/main/resources/deployment/helm/omejdn/templates/configmap.yaml
edc-tests/src/main/resources/deployment/helm/omejdn/templates/deployment.yaml
edc-tests/src/test/java/net/catenax/edc/tests/CatalogStepDefs.java
edc-tests/src/test/java/net/catenax/edc/tests/DataManagementAPI.java
edc-tests/src/test/java/net/catenax/edc/tests/PolicyStepDefs.java
edc-tests/src/test/java/net/catenax/edc/tests/data/BusinessPartnerNumberConstraint.java
edc-tests/src/test/java/net/catenax/edc/tests/data/Constraint.java
edc-tests/src/test/java/net/catenax/edc/tests/data/Permission.java
edc-tests/src/test/resources/net/catenax/edc/tests/features/ContractOffers.feature

New business test for BPN validation

---

edc-extensions/hashicorp-vault/README.md

document hashicorp health check

---

edc-tests/src/test/java/net/catenax/edc/tests/AssetStepDefs.java
edc-tests/src/test/java/net/catenax/edc/tests/CatalogStepDefs.java
edc-tests/src/test/java/net/catenax/edc/tests/ContractDefinitionStepDefs.java
edc-tests/src/test/resources/net/catenax/edc/tests/features/ContractOffers.feature

create business test for 1000 contract offers

---

CHANGELOG.md
edc-dataplane/edc-dataplane-base/pom.xml

add s3 extension to data plane

---

.github/workflows/business-tests.yaml
edc-tests/pom.xml
edc-tests/src/test/java/net/catenax/edc/tests/AssetStepDefs.java
edc-tests/src/test/java/net/catenax/edc/tests/Connector.java
edc-tests/src/test/java/net/catenax/edc/tests/ConnectorSteps.java
edc-tests/src/test/java/net/catenax/edc/tests/Constants.java
edc-tests/src/test/java/net/catenax/edc/tests/ContractDefinitionStepDefs.java
edc-tests/src/test/java/net/catenax/edc/tests/DataManagementAPI.java
edc-tests/src/test/java/net/catenax/edc/tests/Environment.java
edc-tests/src/test/java/net/catenax/edc/tests/NegotiationSteps.java
edc-tests/src/test/java/net/catenax/edc/tests/PolicyStepDefs.java
edc-tests/src/test/java/net/catenax/edc/tests/data/ContractNegotiation.java
edc-tests/src/test/java/net/catenax/edc/tests/data/ContractNegotiationState.java
edc-tests/src/test/java/net/catenax/edc/tests/data/PayMeConstraint.java
edc-tests/src/test/java/net/catenax/edc/tests/util/DatabaseCleaner.java
edc-tests/src/test/java/net/catenax/edc/tests/util/Timeouts.java
edc-tests/src/test/resources/net/catenax/edc/tests/features/ContractNegotiation.feature
edc-tests/src/test/resources/net/catenax/edc/tests/features/ContractOffers.feature
pom.xml

new business test for contract offer verification

---

edc-extensions/dataplane-selector-configuration/README.md

update dataplane selector documentation

---

edc-extensions/hashicorp-vault/README.md

add caten-x configuration example to hashicorp vault README.md

---

deployment/helm/edc-controlplane/README.md
deployment/helm/edc-controlplane/templates/ingress.yaml
deployment/helm/edc-controlplane/values.yaml
deployment/helm/edc-dataplane/README.md
deployment/helm/edc-dataplane/templates/ingress.yaml
deployment/helm/edc-dataplane/values.yaml

ingress name configurable

---

edc-extensions/data-encryption/src/main/java/net/catenax/edc/data/encryption/algorithms/aes/AesAlgorithm.java
edc-extensions/data-encryption/src/main/java/net/catenax/edc/data/encryption/algorithms/aes/AesInitializationVectorIterator.java
edc-extensions/data-encryption/src/test/java/net/catenax/edc/data/encryption/algorithms/aes/AesInitializationVectorIteratorTest.java

update AES-GCM initialization vector creation

---

docs/README.md
docs/data-transfer/Transfer Data.md
docs/release-notes/Version 0.1.1.md
edc-controlplane/README.md
edc-tests/src/main/resources/deployment/helm/all-in-one/templates/secret.yaml
edc-tests/src/main/resources/deployment/helm/all-in-one/values.yaml

~~Draft PR as there are currently 2 TODOs left in the documentation~~
<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

update docu for milestone 6

---

docs/migration/Version_0.1.0_0.1.1.md
docs/release-notes/Version 0.1.1.md

update relesse notes 0.1.1

---

CHANGELOG.md

fix link in changelog

---

docs/migration/Version_0.1.0_0.1.1.md
docs/release-notes/Version 0.1.1.md

update setting name

---

.github/workflows/veracode.yaml

add veracode yaml

---

DEPENDENCIES
docs/development/Release.md
pom.xml

add DEPENDENCIES file

---

DEPENDENCIES
docs/development/Release.md

update release.md with dash token

---

docs/data-transfer/Transfer Data.md

fix transfer data md

---

edc-extensions/cx-oauth2/pom.xml
edc-extensions/cx-oauth2/src/main/java/net/catenax/edc/oauth2/jwt/decorator/ExpJwtDecorator.java
edc-extensions/cx-oauth2/src/main/java/net/catenax/edc/oauth2/jwt/decorator/IatJwtDecorator.java
edc-extensions/cx-oauth2/src/main/java/net/catenax/edc/oauth2/jwt/decorator/IdsAudJwtDecorator.java
edc-extensions/cx-oauth2/src/main/java/net/catenax/edc/oauth2/jwt/decorator/IssJwtDecorator.java
edc-extensions/cx-oauth2/src/main/java/net/catenax/edc/oauth2/jwt/decorator/JWTClaimNames.java
edc-extensions/cx-oauth2/src/main/java/net/catenax/edc/oauth2/jwt/decorator/SubJwtDecorator.java
edc-extensions/cx-oauth2/src/main/java/net/catenax/edc/oauth2/jwt/validation/AudValidationRule.java
edc-extensions/cx-oauth2/src/main/java/net/catenax/edc/oauth2/jwt/validation/ExpValidationRule.java
edc-extensions/cx-oauth2/src/main/java/net/catenax/edc/oauth2/jwt/validation/IatValidationRule.java
edc-extensions/cx-oauth2/src/main/java/net/catenax/edc/oauth2/jwt/validation/NbfValidationRule.java
edc-extensions/cx-oauth2/src/test/java/net/catenax/edc/oauth2/jwt/decorator/ExpJwtDecoratorTest.java
edc-extensions/cx-oauth2/src/test/java/net/catenax/edc/oauth2/jwt/decorator/IatJwtDecoratorTest.java
edc-extensions/cx-oauth2/src/test/java/net/catenax/edc/oauth2/jwt/decorator/IdsAudJwtDecoratorTest.java
edc-extensions/cx-oauth2/src/test/java/net/catenax/edc/oauth2/jwt/decorator/IssJwtDecoratorTest.java
edc-extensions/cx-oauth2/src/test/java/net/catenax/edc/oauth2/jwt/decorator/JtiJwtDecoratorTest.java
edc-extensions/cx-oauth2/src/test/java/net/catenax/edc/oauth2/jwt/decorator/SubJwtDecoratorTest.java
pom.xml

set com.nimbus.josw.jwt version to 8.23

---

edc-extensions/xsuaa-authenticator/pom.xml

fix develop

---

edc-extensions/cx-oauth2/src/test/java/net/catenax/edc/oauth2/jwt/validation/AudValidationRuleTest.java
edc-extensions/cx-oauth2/src/test/java/net/catenax/edc/oauth2/jwt/validation/ExpValidationRuleTest.java
edc-extensions/cx-oauth2/src/test/java/net/catenax/edc/oauth2/jwt/validation/IatValidationRuleTest.java
edc-tests/src/test/java/net/catenax/edc/tests/DataManagementAPI.java

Oauth2 Unit Tests

---

docs/development/Release.md

add one more example call for Release.md Dash

---

charts/edc-controlplane/templates/_helpers.tpl
charts/edc-controlplane/values.yaml
charts/edc-dataplane/templates/_helpers.tpl
charts/edc-dataplane/values.yaml

Extend the helm-charts to have the possibility to add some custom labels via values files.

Add custom Labels to helm-charts.

---

edc-extensions/custom-jsonld/pom.xml
edc-extensions/custom-jsonld/src/main/java/org/eclipse/tractusx/edc/jsonld/CustomJsonLdExtension.java
edc-extensions/custom-jsonld/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
edc-tests/src/test/java/org/eclipse/tractusx/edc/tests/DataManagementAPI.java
pom.xml

To permit multiple BPN numbers constraint

Handle OrConstraint

---

README.md

Signed-off-by: Dominik-Pinsel <dominik.pinsel@daimler.com>

update link to edc logo in README.md

---

edc-tests/src/main/resources/deployment/helm/supporting-infrastructure/Chart.yaml

Signed-off-by: Dominik-Pinsel <dominik.pinsel@daimler.com>

update postgresql version in Chart.yaml supporting-infrastructure

---

charts/tractusx-connector/templates/deployment-controlplane.yaml

remove trailing slash

---

edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile

update alpine from 3.17.0 to 3.17.1 

---

edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/ApiAdapterConfig.java
edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/HttpController.java
edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/dto/ProcessData.java
edc-extensions/control-plane-adapter/src/test/java/org/eclipse/tractusx/edc/cp/adapter/process/contractnegotiation/ContractNegotiationHandlerTest.java

(cherry picked from commit df2988f3290387523b16072862512150faee7cfc)

cp-adapter : code review, rollbacke name change

---

docs/development/postman/collection.json
edc-controlplane/edc-controlplane-base/pom.xml
edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile
edc-controlplane/edc-controlplane-memory/src/main/docker/Dockerfile
edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
edc-controlplane/edc-controlplane-postgresql/src/main/docker/Dockerfile
edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
edc-tests/src/test/java/org/eclipse/tractusx/edc/tests/DataManagementAPI.java
edc-tests/src/test/java/org/eclipse/tractusx/edc/tests/HttpProxyTransferSteps.java
edc-tests/src/test/java/org/eclipse/tractusx/edc/tests/S3FileTransferStepsDefs.java
edc-tests/src/test/resources/org/eclipse/tractusx/edc/tests/features/HttpProxyDataTransfer.feature
pom.xml

Solves [A1IDSC-371](https://jira.catena-x.net/browse/A1IDSC-371)

Configure dynamically HTTP Receiver callback endpoints.

---

.github/workflows/build.yaml
.github/workflows/veracode.yaml

To being able to run the build workflow on support/0.1.2 branch

update build.yml file to the develop version

---

pom.xml

Introduce missing transaction blocks into `SqlPolicyDefinitionStore`

bugfix: fix sql policy definitions issue

---

docs/development/decision-records/2023-03-02_gradle_build/README.md

This PR adds a decision-record regarding the build system of `product-edc`.

docs: decision record build

---

charts/tractusx-connector/templates/deployment-dataplane.yaml

The unused jetty context was causing port conflict for metrics port.

Bugfix: Resolve port conflict.

---

charts/tractusx-connector/values.yaml

bugfix: EDC logs are not visible.

---

docs/development/decision-records/2023-02-27_testing/README.md

This PR contains the decision record about how testing should work in product-edc

docs: create decision record about testing

---

README.md

Add Deprecation message with the new status of "deprecated" for this repository

Add Deprecation message
